2025-03-31 22:48:58 INFO     Finished wandb init.
2025-03-31 22:49:03 INFO     Train dataset: Dataset({
    features: ['id', 'question', 'context', 'answers'],
    num_rows: 12294
})
2025-03-31 22:49:06 INFO     Prompt is: Answer the following question as briefly as possible.
Question: In April, which sportsman married his childhood sweetheart Kim Sears?
Answer: andy murray

Question: From the Latin for argentum, which element, with an atomic number of 47, uses the symbol Ag?
Answer: silver

Question: In which English city will you find the Ashmolean museum?
Answer: oxford

Question: In which city was John Lennon murdered?
Answer: new york

Question: What was Groucho Marx's real first name?
Answer: julius


Traceback (most recent call last):
  File "C:\Users\nikos\anaconda3\envs\nllSAR\Lib\site-packages\huggingface_hub\utils\_http.py", line 409, in hf_raise_for_status
    response.raise_for_status()
  File "C:\Users\nikos\anaconda3\envs\nllSAR\Lib\site-packages\requests\models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://huggingface.co/meta-llama/Llama-3.2-1B/resolve/main/config.json

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\nikos\anaconda3\envs\nllSAR\Lib\site-packages\transformers\utils\hub.py", line 403, in cached_file
    resolved_file = hf_hub_download(
                    ^^^^^^^^^^^^^^^^
  File "C:\Users\nikos\anaconda3\envs\nllSAR\Lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikos\anaconda3\envs\nllSAR\Lib\site-packages\huggingface_hub\file_download.py", line 961, in hf_hub_download
    return _hf_hub_download_to_cache_dir(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikos\anaconda3\envs\nllSAR\Lib\site-packages\huggingface_hub\file_download.py", line 1068, in _hf_hub_download_to_cache_dir
    _raise_on_head_call_error(head_call_error, force_download, local_files_only)
  File "C:\Users\nikos\anaconda3\envs\nllSAR\Lib\site-packages\huggingface_hub\file_download.py", line 1596, in _raise_on_head_call_error
    raise head_call_error
  File "C:\Users\nikos\anaconda3\envs\nllSAR\Lib\site-packages\huggingface_hub\file_download.py", line 1484, in _get_metadata_or_catch_error
    metadata = get_hf_file_metadata(
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikos\anaconda3\envs\nllSAR\Lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikos\anaconda3\envs\nllSAR\Lib\site-packages\huggingface_hub\file_download.py", line 1401, in get_hf_file_metadata
    r = _request_wrapper(
        ^^^^^^^^^^^^^^^^^
  File "C:\Users\nikos\anaconda3\envs\nllSAR\Lib\site-packages\huggingface_hub\file_download.py", line 285, in _request_wrapper
    response = _request_wrapper(
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\nikos\anaconda3\envs\nllSAR\Lib\site-packages\huggingface_hub\file_download.py", line 309, in _request_wrapper
    hf_raise_for_status(response)
  File "C:\Users\nikos\anaconda3\envs\nllSAR\Lib\site-packages\huggingface_hub\utils\_http.py", line 426, in hf_raise_for_status
    raise _format(GatedRepoError, message, response) from e
huggingface_hub.errors.GatedRepoError: 403 Client Error. (Request ID: Root=1-67eaffc2-07f694dd0df2c8b95e22ef9c;56529c15-e6a2-4184-93ac-bbdd15f16860)

Cannot access gated repo for url https://huggingface.co/meta-llama/Llama-3.2-1B/resolve/main/config.json.
Your request to access model meta-llama/Llama-3.2-1B is awaiting a review from the repo authors.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\nikos\PycharmProjects\nllSAR\src\generate_answers.py", line 263, in <module>
    main(args)
  File "C:\Users\nikos\PycharmProjects\nllSAR\src\generate_answers.py", line 89, in main
    model = utils.init_model(args)
            ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikos\PycharmProjects\nllSAR\src\utils\utils.py", line 278, in init_model
    model = HuggingfaceModel(
            ^^^^^^^^^^^^^^^^^
  File "C:\Users\nikos\PycharmProjects\nllSAR\src\models\huggingface_models.py", line 113, in __init__
    self.tokenizer = AutoTokenizer.from_pretrained(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikos\anaconda3\envs\nllSAR\Lib\site-packages\transformers\models\auto\tokenization_auto.py", line 877, in from_pretrained
    config = AutoConfig.from_pretrained(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikos\anaconda3\envs\nllSAR\Lib\site-packages\transformers\models\auto\configuration_auto.py", line 1017, in from_pretrained
    config_dict, unused_kwargs = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikos\anaconda3\envs\nllSAR\Lib\site-packages\transformers\configuration_utils.py", line 574, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikos\anaconda3\envs\nllSAR\Lib\site-packages\transformers\configuration_utils.py", line 633, in _get_config_dict
    resolved_config_file = cached_file(
                           ^^^^^^^^^^^^
  File "C:\Users\nikos\anaconda3\envs\nllSAR\Lib\site-packages\transformers\utils\hub.py", line 421, in cached_file
    raise EnvironmentError(
OSError: You are trying to access a gated repo.
Make sure to have access to it at https://huggingface.co/meta-llama/Llama-3.2-1B.
403 Client Error. (Request ID: Root=1-67eaffc2-07f694dd0df2c8b95e22ef9c;56529c15-e6a2-4184-93ac-bbdd15f16860)

Cannot access gated repo for url https://huggingface.co/meta-llama/Llama-3.2-1B/resolve/main/config.json.
Your request to access model meta-llama/Llama-3.2-1B is awaiting a review from the repo authors.
